template/go-armhf/Dockerfile, template/go/Dockerfile
The go templates check for formatting, but exclude vendored files in the template folder itself ignoring any additional vendor folder in the function folder.
---
- Add extra eclusion for function/vendor folder when checking file formatting
Fixes OpenFaas/templates#1
=> Allow vendor dir in golang's function folder

template/csharp/root.csproj
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
Fixes https://github.com/openfaas/faas-cli/pull/306
.NET Core globs - so it already includes the class Library as part of the .exe rather than compiling a separate module/library as desired. This change removes the recursive glob from the root project so the references work correctly without duplicate types.
=> Fix CSharp build-time warning

template/go-armhf/Dockerfile, template/go/Dockerfile
This is to give the build stage an alias so that COPY instructions are clearer: `--from=builder` instead of `--from=0`
Giving the build stage an alias makes reading the Dockerfile more comprehensible
Only tested with `go` template, armhf is not tested
```
faas-cli new test-go-builder-stage --lang=go
faas-cli build -f test-go-builder-stage.yml
faas-cli deploy -f test-go-builder-stage.yml
echo "test" | faas-cli invoke test-go-builder-stage
```
=> set builder alias for build stage

template/csharp/Dockerfile
This commit picks up unfinished community PRs from faas-cli repo
with some input from @iyovcheva.
Testing has been done with a nuget package (Newtonsoft.Json) on
Docker for Mac with Kubernetes and faas-netesd:0.5.0
https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonConvert.htm
Also adds (missing) healthcheck for Swarm
Closes #24
Signed-off-by: Alex Ellis (VMware) <alexellis2@gmail.com>
Add package:
```
dotnet add package Newtonsoft.Json
```
Function code:
```
using System;
using System.Text;
using Newtonsoft.Json;
namespace Function
{
public class Movie {
public string Name {get;set;}
}
public class FunctionHandler
{
public void Handle(string input) {
string json = @"{
'Name': 'Bad Boys',
'ReleaseDate': '1995-4-7T00:00:00',
'Genres': [
'Action',
'Comedy'
]
}";
Movie m = …
```
=> Move C# template to non-root user

template/python-armhf/Dockerfile, template/python-armhf/template.yml, template/python/Dockerfile, template/python/template.yml, template/python3-armhf/Dockerfile, template/python3-armhf/template.yml, template/python3/Dockerfile, template/python3/template.yml
This change allows the python3 template to make use of the new faas-cli feature  - support for building native modules i.e. C/C++.
The packages listed in `template.yml` will be built if a `--build_option=dev` flag is used with `faas-cli` build.
Thanks to @kenfdev for sharing a function to test with.
[faas-pandas-example](https://github.com/kenfdev/faas-pandas-example)
[#28](https://github.com/openfaas/templates/issues/28)
Tested together with [faas-cli/#414](https://github.com/openfaas/faas-cli/pull/414)
=> Edit python templates to support `build_options` feature

template/python-armhf/template.yml, template/python/template.yml, template/python3-armhf/template.yml, template/python3/template.yml
With this change `git` is added to dev build option packages for all python templates. 
The  reason  behind is that  some modules installations require cloning source from github
Referenced in pull [#414](https://github.com/openfaas/faas-cli/pull/414)
=> Add `git` to dev build option

template/python/template.yml, template/python3/template.yml
With this change `python` and `python3` templates are updated to
support building mysql packages
Discussed with @alexellis on slack
`requirements.txt`:
```
mysqlclient
mysql-connector-python-rf
```
=> Add mysql build option

template/ruby/Dockerfile
This fixes ruby template to set app group properly. 
Before used to add GEO data for user, after the change adds group to user
Fixes #41
Manually tested with `docker run -ti <image> sh` and by building function template.
=> Fix user group for Ruby

template/dockerfile/function/Dockerfile
This fixes dockerfile template to set app group properly.
Before used to add GEO data for user, after the change adds group to user
Fixes #41
Manually tested with `docker run -ti <image> sh` and by building function template.
=> Fix user group for dockerfile

template/ruby/Dockerfile
Ruby template is creating non-root user, but still used to run as
a root. This change updates to run as app instead
Fixes #68 
1. `faas-cli new --lang ruby ruby-test`
2. `faas-cli up`
3. 
```
$ docker run -ti ruby-test:latest sh
app
```
4. 
```
$ faas-cli invoke
Hello world from the Ruby template
```
5.
`Gemfile`:
```
gem 'nokogiri'
```
`handler.rb`:
```
require 'nokogiri'
class Handler
def run(req)
html_doc = Nokogiri::HTML("<html><body><h1>Some message here</h1></body></html>")
return html_doc
end
end
```
```
$ faas-cli up --build-option dev
$ faas-cli invoke
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><h1>Some message here</h1></body></html>
```
=> Run ruby as non-root

template/dockerfile/function/Dockerfile, template/go-armhf/Dockerfile, template/go/Dockerfile, template/java8/Dockerfile, template/node-arm64/Dockerfile, template/node-armhf/Dockerfile, template/node/Dockerfile, template/python-armhf/Dockerfile, template/python/Dockerfile, template/python3-armhf/Dockerfile, template/python3/Dockerfile, template/ruby/Dockerfile
By adding `EXPOSE 8080` to all templates we make them usable with
`docker run -P` which can bind a random local port for
testing / debug
Resolves #74
=> Add "EXPOSE 8080" to all templates

template/ruby/Dockerfile
I noticed some inconsistencies in the whitespace ruby Dockerfile which lead to *ugly* output when building functions:
```
Step 5/18 : COPY Gemfile                .
...
Step 6/18 : COPY index.rb           .
...
Step 7/18 : COPY function           function
...
```
Indentation changes
=> Ruby Dockerfile whitespace cleanup

template/ruby/function/handler.rb, template/ruby/template.yml
Formats code according to usual ruby styling
In Ruby, code is usually indented with 2 spaces instead of 4
https://github.com/rubocop-hq/ruby-style-guide#source-code-layout
It's not, but whenever I create a new function I find myself auto-indenting this file :smile:
=> update Ruby code according to usual ruby styles

template/java8/entrypoint/src/main/java/com/openfaas/entrypoint/App.java, template/java8/model/src/main/java/com/openfaas/model/IRequest.java, template/java8/model/src/main/java/com/openfaas/model/Request.java, template/java8/model/src/test/java/RequestTest.java
Since OpenFaaS now supports path parameters we should update the
template to be able to use path for passing them. Until now this
was supported only by the body or by query
Fixes #77 
Running the unit test with
```
cd template/java8/model
$ gradle build
BUILD SUCCESSFUL in 2s
14 actionable tasks: 10 executed, 4 up-to-date
```
Tested with function.
Handler.java:
```
package com.openfaas.function;
import com.openfaas.model.IHandler;
import com.openfaas.model.IResponse;
import com.openfaas.model.IRequest;
import com.openfaas.model.Response;
import java.io.*;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.*;
import java.nio.file.Files;
import java.nio.file.Paths;
public class Handler implements …
```
=> Add getPath to Java8 template

README.md, template/csharp-armhf/function/FunctionHandler.cs, template/csharp/function/FunctionHandler.cs, template/dockerfile/function/Dockerfile, template/node-arm64/Dockerfile, template/python-armhf/Dockerfile, template/python3-armhf/Dockerfile, template/python3/Dockerfile
It does change the C# example to use string interpolation instead of string.Format and removes some blank lines that are indicated by visual studio code. 
#127 
#126 
I tested it on my local machine. 
Minor improvements.
I deployed the faas-stack locally with your deploy_stack.sh.
Then I created a new directory. Copied the from the repo templates (I did not use template pull) into it.
Then I did a 
```
$ faas-cli new --lang chsarp helloworld-new
$ faas-cli build -f helloworld-new.yml
$ faas-cli deploy -f helloworld-new.yml
$ echo "foobar" |faas-cli invoke helloworld-new 
Hi there - your input was: foobar
```
I also did that for the python3 template.
```
$ faas-cli new --lang python3 helloworld-python
$ faas-cli build -f helloworld-python.yml 
$ faas-cli deploy -f helloworld-python.yml 
$ …
```
=> Minor improvements (string interpolation in the C# example, removes some blanks)

template/csharp-armhf/Program.cs, template/csharp/Program.cs
As discussed in #107 this PR changes the way the `csharp` template reads the console so that newline characters are not converted.
Issue #107 
Fixes #107
I reran the steps to reproduce from #107
=> Fixing console reading for csharp template

template/java8/Dockerfile
This commit upgrades the openjdk version to the earliest that supports
cgroup memory limits. It also applies the JVM arguments required to
enable the support.
This change is needed for the JVM to recognize the actual memory
made available to it via the container instead of believing it has
access to the amount of memory possessed by the node running the
container.
Signed-off-by: Chad Taylor <taylor.thomas.c@gmail.com>
This PR updates the java8 template to use a newer version of the OpenJDK that supports cgroup memory limits. It also updates the JVM to use the flags necessary to enable the cgroup memory limits support in production.
Fixes #129
Using this template and the function defined in #129, I was able to successfully invoke the function without crashing the container and receiving a …
=> Update the java8 template to honor cgroups memory limits

.gitignore, template/go/Dockerfile, template/go/template.yml, template/python3/template.yml
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
A user reported a desire to build OpenFaaS functions with CGO
this can now be achieved by passing a build arg of CGO_ENABLED=1
and with build_options dev.
User reported wanting to build SQLite
Tested with the "simple" sample from https://github.com/mattn/go-sqlite3
```go
package function
import (
"database/sql"
"fmt"
"log"
"os"
_ "github.com/mattn/go-sqlite3"
)
// Handle a serverless request
func Handle(req []byte) string {
integrationTest()
return fmt.Sprintf("Hello, Go. You said: %s", string(req))
}
func integrationTest() {
os.Remove("./foo.db")
db, err := sql.Open("sqlite3", "./foo.db")
if err != nil {
log.Fatal(err)
}
defer db.Close()
sqlStmt := `
create table foo (id integer not null primary key, name text);
delete from foo;
`
_, err = …
```
=> Enable CGO as an option for Go

template/php7/Dockerfile
Signed-off-by: Richard Gee <richard@technologee.co.uk>
Remove the call out to github in favour of using the new Watchdog image.
Since the watchdog image is multi-arch, this should also have the effect of enabling php7 on arm.  Will test this when close to a raspberry pi.
Updates php7 to follow the new pattern.  
Potentially enables php7 on arm.
Fixes #147
Closes #148 
Used the Dockerfile locally
Created a new function
Ran `faas up`
Ran faas invoke on the new function
=> Update php7 Dockerfile to use watchdog image

template/csharp-armhf/Dockerfile, template/csharp/Dockerfile, template/dockerfile-armhf/function/Dockerfile, template/dockerfile/function/Dockerfile, template/go-armhf/Dockerfile, template/go/Dockerfile, template/python/Dockerfile, template/python3/Dockerfile
Signed-off-by: Richard Gee <richard@technologee.co.uk>
Updates the templates that were previous moved to the hardware architecture specific Watchdog images so that they all use the multi-arch equivalent.
Reduced maintenance. More generic pattern.
Fixes #
Local builds
Deployed
Invoked
=> Update watchdog image to multi-arch 0.13.4

template/node/function/handler.js, template/node/index.js
Signed-off-by: Patricio Diaz <padiazg@gmail.com>
This template introduces the possibility of using Promise or Async/Await on the handler function, in addition of the callback approach used before.
In index.js the value returned by handler.js is checked to figure out if it is the final result or is a Promise so it can be retrieved and handled properly.
We need to handle the latest asynchronicity mechanism provided by the language, which are Promises and Async/Await
Fixes issue #92 
Fixes #92
```bash
$ faas new node-cb --lang node --prefix padiazg
```
handler.js
```js
"use strict"
// A simple delay function
const delayCallback = cb => {
const min = 0; // 0 sec
const max = 2; // 2 sec
const delay = Math.round((Math.random() * (max - min) + min));
setTimeout(() => cb(delay),  delay * 1000);
} …
```
=> Node.js template to support promise/async/await

template/ruby/Dockerfile
bumping ruby & alpine version in dockerfile
ruby 2.7 was released recently
alpine 3.7 reached its EOL.
manually build (before and after the change).
`docker run -p 8080:8080 ruby-template:0.1` 
and then
`curl localhost:8080`
which returned
`Hello world from the Ruby template` (as expected)
docker log:
```
2020/01/05 13:33:25 Forking fprocess.
2020/01/05 13:33:25 Wrote 35 Bytes - Duration: 0.072239 seconds
```
newer version with backward compatibility.
=> bump ruby version in template dockerfile

template/node12/index.js
This change adds the use of 2 environment variables: `RAW_BODY` and `MAX_JSON_SIZE`, allowing users to receive the
request body as a buffer (the 'raw' body) as well as the ability to set the maximum
JSON body size.
The raw body is required when processing Stripe webhooks
The max JSON body size is defaulted to a low limit from body-parser which has caused
issues with users in the past.
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>
There was some discussion in the issue linked below. I've decided to implement the change in this was so that it was a more overall change rather than adding it to a specific verb (`POST`) to avoid surprising results when a user sets the `RAW_BODY` to true, it won't be limited only to post requests. 
This also means that `PUT`, `DELETE`, and `GET` requests …
=> Add env vars to use raw body and set max json size

template/go-armhf/Dockerfile, template/go-armhf/go.mod, template/go-armhf/main.go, template/go/Dockerfile, template/go/go.mod, template/go/main.go
Add support for nested go modules by supporting the GO_REPLACE.txt file and the build args for GO111MODULE and GOFLAGS.  
The version of Go is upgraded to the latest major version: 1.13
This largely replicates the module support and structure of the [go-middleware-template](https://github.com/openfaas-incubator/golang-http-template/tree/master/template/golang-middleware)
Fixes #189
I have created a demo repo to show that the template works as expected. https://github.com/LucasRoesler/gomodule-template-test
It specifically show how the nested module support works.  I have also manually tested the simpler flat module and non-module mode.
Existing functions should continue to work as expected. The only changes should be controlled by the build arg
=> Support go modules

template/node12/Dockerfile, template/node12/function/package.json, template/node12/package.json, template/node12/template.yml
Run unit tests for node12 if present
This change allows npm test to be run in during the Docker build
of code using the node12 template. Unfortunately the package.json
that the template generated will fail for any users who take this
newer version, unless they edit the "test" section of their
package.json file.
This is because it is hard-coded to "exit 1", the newer change
is set to "exit 0" and to only show a warning about tests
missing. It will not affect any functions that are created
after this time.
Tested with 3 scenarios:
* Tests given which passed, with mocha and chai
* Tests given which failed with mocha and chai
* No tests given at all
This was change requested by a user on Slack, but is consistent with the Java and …
=> Run unit tests for node12 if present

template/node-armhf/Dockerfile
This updates the node-armhf function template to use a non-root
user. Creates `app` system user  and `app` group
Fixes #23 #41
Local build of simple node-armhf function
=> Update node-armhf template to use non-root user

README.md, template/python3-debian/Dockerfile, template/python3-debian/function/handler.py, template/python3-debian/index.py, template/python3-debian/template.yml
- Copy the python3-debian template from https://github.com/openfaas-incubator/python3-debian
- Update the dockerfile to be non-root, this adapts the same
modifications/commands that the alpine dockerfile uses, but of course  adapted to debian
Fixes openfaas-incubator/python3-debian#10
Fixes openfaas-incubator/python3-debian#7
I tested it by creating a new echo function 
```sh
faas-cli new echo --lang python3-debian
```
I then built it using 
```sh
$ faas-cli build -f echo.yml 
$ docker run --rm -d -p 8080:8080 echo:latest
$ curl http://localhost:8080 -d "this is a test message"
this is a test message
```
I then verified that `ADDITIONAL_PACKAGE` worked as expected using
```sh
faas-cli build -f echo.yml --build-arg ADDITIONAL_PACKAGE='curl build-essential'
$ docker run --rm -d -p 8080:8080 …
```
=> Graduate python3-debian from incubator

README.md
I updated the README to reflect the versions in the template Dockerfile's.
=> update README with current versions

template/node12/index.js
=> Add options verb to node12 template

Makefile, verify.sh
Change the makefile to use `bash` not `sh` for the script.
Turns out my laptop has sh symlinked to bash so that's why make worked locally
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
Fixes #
see check suite
=> Fix GH actions by using bash not sh

template/go/Dockerfile, template/node/Dockerfile, template/node12/Dockerfile, template/php7/Dockerfile, template/python/Dockerfile, template/python3-debian/Dockerfile, template/python3/Dockerfile, template/ruby/Dockerfile
Signed-off-by: Utsav Anand <utsavanand2@gmail.com>
Change the following templates to support multi-arch buildx builds:
go
node
node12
php7
python
python3
python3-debian
ruby
The PR will add the freedom to build and deploy OpenFaaS function to multiple CPU architectures.
Functions can be built locally or a CI env like Github Actions which supports buildx, and deployed on most common architectures, like amd64, arm64, or armv7
Fixes #226 
No user impact to existing users because of the tests we have been running for the incubator templates, running functions across environments and architectures.
=> Make templates multi-arch

template/php7/function/composer.json, template/php7/function/src/Handler.php
This fixes a few warning you get when using the PHP template:
- naming convention (missing `/`) which will become an error with composer v2: `Deprecation warning: Your package name function-php7.2 is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$". Make sure you fix this as Composer 2.0 will error.`
- missing license
To avoid fixing every time.
- `cd` into folder
- `composer validate`
As a template it shouldn't affect any existing users.
=> Fixing warnings in PHP template

template/node12/index.js
Add configurable raw limit
This change means users can send a raw body of over 100KB, previously the body-parser middleware was restricting this size.
Fixes: #245
Closes: #246
Tested by the user in #245 and by another user on Slack who also asked for this today.
A change will be required in the openfaas/docs repo.
=> Add configurable raw limit

README.md
Fixed hyperlinks to `node12` and `node14` templates source code so that they are located in the matching template row.
Minor documentation issue that can be confusing.
Fixes #250.
* Browsed README.md in the adequate branch on github.com ;
* Clicked the links ;
* Verified that the correct directory was displayed.
=> Minor documentation fix - links to node12 and node14 in README.md

template/node14/Dockerfile
Signed-off-by: Guillaume Grussenmeyer <ggrussenmeyer@protonmail.com>
Update `node` Docker image version to `14-alpine` in `node14/Dockerfile` (was `12-alpine`).
Fixes #253 
By verifying the output of `docker run node14-ci node --version`.
Users that thought they were running Node.js v14 when using the `node14` template were actually running v12.
After this PR they'll be actually running v14.
I'm unable to evaluate the effective impact; YMMV.
=> Fixes node14 Dockerfile to reference the correct Node.js Docker image version

template/node12/index.js, template/node14/index.js
Add custom status when failing a node12/14 request
Tested with a 401 status before failing the message and saw
the code as expected.
Also tested with just calling fail, and saw the 500 code.
Closes #258 and Fixes: #257
N/a - no harm.
=> Add custom status when failing a node12/14 request

template/java11-vert-x/Dockerfile, template/java11-vert-x/entrypoint/build.gradle, template/java11-vert-x/function/build.gradle
Update java11-vertx to use a shadow jar
@koogordo suggested that using a shadow jar reduces the total size of functions using this template. Early testing showed up to 100MB in saving, and removed the zip/unzip stage from the build, making it quicker.
Tested by running a docker build inside the template folder and running the container with docker, the code continued to work as expected.
Optimization, plus an upgrade to Gradle 7.3.3
The change in gradle version may mean changing "compile" to "implementation" within your gradle scripts.
=> Update java11-vertx to use a shadow jar

template/go/Dockerfile
Allow static files to be published into final image for Go template
Allows code to be published into final image, without leaking additional source code into container.
```go
package function
import (
"fmt"
"io/ioutil"
"os"
"log"
)
// Handle a serverless request
func Handle(req []byte) string {
data, err := ioutil.ReadFile("./static/hostname")
if err != nil {
log.Println(err)
os.Exit(-1)
}
return fmt.Sprintf("File contents: %s", string(data))
}
```
This is a *breaking change* for existing users who rely on folder names such as `templates` or `dataset.json` within their published image.
Now, put these files into the `static` folder and read them from `./static/templates/index.html` and so forth.
A note will be published in the …
=> Allow static files to be published into final image for Go template

README.md, template/php8/Dockerfile, template/php8/function/composer.json, template/php8/function/php-extension.sh, template/php8/function/src/Handler.php, template/php8/index.php, template/php8/php-extension.example.sh, template/php8/php-extension.sh-example, template/php8/readme.md, template/php8/template.yml
I added a new subfolder in the `template` directory, containing a PHP 8 template, including the `:latest` Composer image.
Further I had to remove the Phalcon example on installing extensions, because Phalcon right now has no PHP 8 support. It's being worked on, but I don't know when it will be available, so I removed it. The example is still available in the PHP 7 template.
As described in #293 , PHP 7's end of life is near, so there is a need for a fresh PHP 8 template. The old template was also locked to an old version of Composer, hence I updated the Dockerfile to always use the latest version of Composer (v2). Also updated classic-watchdog version.
Fixes #293.
I verified that the build including the extensions example works, and did some simple tests by deploying the resulting image …
=> Provide a PHP 8 template

template/python3-debian/Dockerfile, template/python3/Dockerfile
Add a build arg to the python3 templates so that developers can pin the python version.
Relates to https://github.com/openfaas/python-flask-template/pull/67 and keeps the Python templates consistent.
Manually tested with the default "echo" function
None, the current templates are equivalent and track the default latest python3 tag, the only change is the support to pin it to a specific tag via a build arg.
=> feat: support build arg to pin the python3 version

template/node/template.yml
change typo from Go to node
Fixes #
=> minor: fix classic node template description
