- template/python-armhf/Dockerfile
- template/python3/Dockerfile
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>
https://github.com/openfaas/faas-cli/issues/284
> fixes issue with requirements install for python3 and python-armhf

- template/dockerfile/function/Dockerfile
- template/dockerfile/template.yml
Issue openfaas/faas-cli#271
PR openfaas/faas-cli#275
> add dockerfile language

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
**Description**
* Added github template for issue and pull request.
* Added contribution guide.
Cc / @alexellis
> Add GitHub

- template/csharp/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go-armhf/Dockerfile
- template/go/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
This change required to make templates use 0.7.6 release version of
watchdog. This version of watchdog has enhanced configuration.
Release link: https://github.com/openfaas/faas/releases/tag/0.7.6
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>
Fixes #
I have tested few templates on Docker for Mac.
> Bump all templates to the 0.7.6 version of the watchdog

- template/csharp/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go-armhf/Dockerfile
- template/go/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/python-armhf/Dockerfile
- template/python3-armhf/Dockerfile
- template/ruby/Dockerfile
Signed-off-by: Ivana Yovcheva <iyovcheva@vmware.com>
Raised by @alexellis 
Fixes #
> Update watchdog version to 0.7.9 in function templates

- template/ruby/Dockerfile
- template/ruby/template.yml
This change allows the ruby template to make use of the new faas-cli feature  - support for building native modules i.e. C/C++.
The packages listed in `template.yml` will be built if a `--build-option=dev` flag is used with `faas-cli` build.
E.g. `faas-cli build <func> --lang ruby --build-option dev`
[#28](https://github.com/openfaas/templates/issues/28)
Uses pull [faas-cli/#414](https://github.com/openfaas/faas-cli/pull/414)
Gemfile:
```
source 'https://rubygems.org'
gem 'bundler'
gem 'rake'
gem 'rake-compiler'
gem 'rspec', '>= 3.0.0'
gem 'rubocop', '>= 0.36.0'
gem 'sshkit', '>= 1.9.0'
gem 'yard'
gem 'libssh'
```
Build command
```
faas-cli-darwin build --lang ruby --build-option dev
```
> Edit ruby template to support `build_options` feature

- template/python-armhf/template.yml
- template/python/template.yml
- template/python3-armhf/template.yml
- template/python3/template.yml
With this change all python templates are updated to support
building pillow
Discussed with @alexellis to document how to build pillow with build-options
`requirements.txt`:
```
pillow
```
Build:
`faas build --build-option dev --build-option pillow`
> Add pillow build option

- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3-armhf/Dockerfile
- template/python3/Dockerfile
This fixes all python templates to set app group properly. 
Before used to add GEO data for user, after the change adds group to user
Fixes [#41](https://github.com/openfaas/templates/issues/41).
Manually tested with `docker run -ti <image> sh`.
Tested building simple functions with every template.
> Fix user group for Python

- template/go/template.yml
- template/node/template.yml
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>
Fixes #
> Added welcome message for node and golang template

- template/java8/entrypoint/src/main/java/com/openfaas/entrypoint/App.java
- template/java8/model/src/main/java/com/openfaas/model/IRequest.java
- template/java8/model/src/main/java/com/openfaas/model/Request.java
- template/java8/model/src/test/java/RequestTest.java
This changes add functionality to parse request query paramaters for java template.
Signed-off-by: Richhpal Gora <richhpalgora1610@gmail.com>
Fixes #
> Added query parameters support for java template

- template/go/template.yml
- template/node/template.yml
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>
Fixes #
> Updated welcome message field to welcome_message

- template/csharp/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go-armhf/Dockerfile
- template/go/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3-armhf/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
With this commit all the Dockerfiles that download openfaass
version are updated to pull the latest release
Signed-off-by: Martin Dekov (VMware) <mdekov@vmware.com>
Update Dockerfile to download latest 0.8.9 version instead of 0.8.0 in templates.
Change template Dockerfiles link from 
```curl -sSL https://github.com/openfaas/faas/releases/download/0.8.0/fwatchdog > /usr/bin/fwatchdog \```
to
```curl -sSL https://github.com/openfaas/faas/releases/download/0.8.9/fwatchdog > /usr/bin/fwatchdog \```
Fixes #
> Update Dockerfiles to pull latest openfaas version 0.8.9

- template/csharp/Dockerfile
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>
This commit upgrades the csharp template to the latest .NET runtime
to take advantage of the new features around app performance
Fixes #58 
Created new test function and deployed locally to Swarm. Also verified with existing functions that were deployed to Azure Swarm instance. Everything works as expected.
> Upgrade csharp template to dotnet 2.1

- .travis.yml
- verify.sh
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>
This adds a script that will be run with a CI system to
validate the templates are able to build and output
a value verifying that they are functional in the most
basic functionality of returning a value
Fixes #54 
Ran script locally:
```
./verfiy.sh
```
Also, ran build via [TravisCI](https://travis-ci.org/burtonr/templates/builds/410620475)
> Add travis.yml and script to validate templates

- template/csharp/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go-armhf/Dockerfile
- template/go/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3-armhf/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
Moved the templates from using watchdog 0.8.9 to
latest 0.8.10 version
Signed-off-by: Martin Dekov (VMware) <mdekov@vmware.com>
Moved templates from 0.8.9 to 0.8.10 watchdog version.
Updated the places that mention watchdog version 0.8.9 to use 0.8.10 which is the newest.
It was requested.
Fixes #
> Update watchdog from 0.8.9 to 0.8.10

- README.md
> CONTRIBUTING.md url fixed

- template/csharp/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go-armhf/Dockerfile
- template/go/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3-armhf/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
Bumping up the watchdog to 0.9.4
Signed-off-by: Martin Dekov (VMware) <mdekov@vmware.com>
Bump watchdog in templates to 0.9.4
Requested
Bumps the version
N.A.
> Move watchdog to 0.9.4 in templates

- template/php7/function/php-extension.sh
- template/php7/php-extension.sh-example
- template/php7/readme.md
- template/php7/template.yml
This PR makes some minor tweaks to the documentation of the `php7` template both in the README.md and associated files.
#80
Visual inspection.
> Minor documentation tweaks to php7 template

- .gitignore
- template/csharp/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go/Dockerfile
- template/java8/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/php7/Dockerfile
- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3-armhf/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
Signed-off-by: Alex Ellis (VMware) <alexellis2@gmail.com>
- Updates the watchdog to the latest version
- Moves to Alpine 3.8 as part of #70 
CSharp template tested due to structural changes to improve build speed.
Other templates will be tested by CI
Updates to components. None of above
> Update watchdog and to Alpine 3.8

- template/node/index.js
This fixes the issue descripted in #89.
Fixes #89 
1. I created a new funtion via: ```faas-cli new --lang node handler-test```
2. I modified ```handler-test/handler.js```: ```module.exports = (context, callback) => { callback(undefined, undefined); }```
3. Invoked the function. ```echo hello | faas-cli invoke handler-test```
With the current version of the template the function threw this error:
```
TypeError: Invalid data, chunk must be a string or buffer, not undefined
at Socket.write (net.js:701:11)
at handler (/home/app/index.js:18:28)
at module.exports (/home/app/function/handler.js:4:5)
at getStdin.then.val (/home/app/index.js:11:5)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
```
With my changes it returned nothing.
> Updated node template for when user returns nil

- template/java8/Dockerfile
Signed-off-by: Radoslav Dimitrov <rdimitrow@gmail.com>
Closing also #76
> Bump of-watchdog to version 0.4.1

- template/php7/template.yml
> fix typo in php7 template's note

- template/java8/Dockerfile
Signed-off-by: Radoslav Dimitrov <rdimitrow@gmail.com>
Bump of-watchdog version to 0.4.2
Fixes #
Not tested yet!
> Bump of-watchdog version to 0.4.2

- README.md
Adding table with the templates in the repository which
describes in general the templates along with reference
to the docs
Signed-off-by: Martin Dekov (VMware) <mdekov@vmware.com>
Added a table which contains general information for the templates in the repository
Adding table with template name, language, version of the language, linux base and link to the template in the repository, also added sentence for the docs
> Note: Some places I marked with N/A since was unable to find information in Dockerhub for the linux base and version of the language in that image
Fixes #100 
N.A. documentation adding
> Add table with templates in the repo

- template/java8/Dockerfile
Signed-off-by: Omer Zamir <zamir98@gmail.com>
Bump of-watchdog version to 0.4.6
Updating of-watchdog version as @alexellis requested in [here](https://github.com/openfaas-incubator/node10-express-template/pull/2#issuecomment-450489840)
> Increase of-watchdog version to 0.4.6

- template/csharp/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go-armhf/Dockerfile
- template/go/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/php7/Dockerfile
- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3-armhf/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
Signed-off-by: Ron Rivera <roncrivera@gmail.com>
The existing templates still use 0.9.6 version of the watchdog. We need to update the watchdog version for all the templates to pull the latest binary (0.9.14) which includes fixes to memory leak.
Fixes issue #115
> Bump watchdog version to 0.9.14

- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3-armhf/Dockerfile
- template/python3/Dockerfile
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
Changed the templates to allow a random UID for Python2/3
Breakage with OpenShift / hard-coded user-id in faas-netes
Tested on Docker directly. Help from @lucasroesler and some
inspiration from the OpenShift source to image work.
* `./uptime/handler.py `
```
import requests
def handle(req):
"""handle a request to the function
Args:
req (str): request body
"""
return requests.get("https://api.ipify.org?format=json").text
```
* `./uptime/requirements.txt`
```
requests
```
Before:
This failed at invoke:
```
docker rm -f uptime ; docker run --name uptime --user 10000:0 -p 8001:8080 -ti uptime
```
After it passed with `python` (2.7) and `python3`👍
> Allow any user-id

- template/csharp-armhf/Dockerfile
- template/csharp/Dockerfile
- template/dockerfile-armhf/function/Dockerfile
- template/dockerfile-armhf/template.yml
- template/go-armhf/Dockerfile
- template/go/Dockerfile
- template/go/template.yml
- template/python/Dockerfile
- template/python3/Dockerfile
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
This multi-stage build means there is no need to install curl
and ca-certs just to pull the watchdog binary. Instead we can
pull in the binary from the new watchdog image.
This covers #11 for:
- Go
- Python 2 / 3
- CSharp
- Dockerfile
Tested with x86_64 on a Swarm node by creating new functions in each language and invoking them.
> Update Go template to use watchdog from image

- CONTRIBUTING.md
- template/java8/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/python-armhf/Dockerfile
- template/python3-armhf/Dockerfile
- template/ruby/Dockerfile
Signed-off-by: Krystian Wojcicki <kwojcicki@sympatico.ca>
Fixes #
> Updated to multidocker files to get watchdog

- template/csharp-armhf/Dockerfile
- template/csharp/Dockerfile
- template/dockerfile-armhf/function/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go-armhf/Dockerfile
- template/go/Dockerfile
- template/java12/Dockerfile
- template/java8/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/php7/Dockerfile
- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3-armhf/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
> Update watchdog versions

- template/csharp-armhf/Dockerfile
- template/csharp/Dockerfile
- template/dockerfile-armhf/function/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go-armhf/Dockerfile
- template/go/Dockerfile
- template/node-arm64/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/php7/Dockerfile
- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/python3-armhf/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
Watchdog versions were updated to latest at each Dockerfile
Watchdog version was changed from 0.18.0 to 0.18.1 at each Dockerfile
Fixes #
- [x ] My code follows the code style of this project.
- [x ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
> [UPD]  Watchdog versions were updated to latest

- .github/workflows/only-ci.yaml
The OpenFaas approach is to build on all branches and PRs via GitHub Actions. This PR updates this repo to follow that pattern
https://github.com/openfaas/templates/actions/runs/354389027
> Updated to build all branches and PRs

- template/java11-vert-x/README.md
- template/java11-vert-x/settings.gradle
- template/java11-vert-x/template.yml
> java11-vert-x: words correct: java8 -> java11

- README.md
Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>
Corrected the Build badge Job name from build to ci-only
Fixes #236
> corrected workflow job name to ci-only

- template/csharp/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go/Dockerfile
- template/java11-vert-x/Dockerfile
- template/java11/Dockerfile
- template/node/Dockerfile
- template/node12-debian/Dockerfile
- template/node12/Dockerfile
- template/node14/Dockerfile
- template/php7/Dockerfile
- template/python/Dockerfile
- template/python3-debian/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
Bump watchdogs for quick shutdowns
Fixes: #270
Tested in the Go HTTP templates
None expected.
> Bump watchdogs for quick shutdowns

- template/java11-vert-x/Dockerfile
- template/java11/Dockerfile
- template/node12-debian/Dockerfile
- template/node12/Dockerfile
- template/node14/Dockerfile
- template/node16/Dockerfile
- template/node17/Dockerfile
Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>
of-watchdog version to 0.9.3
of-watchdog version to 0.9.3
Fixes #283
1. Made changes into template
2. Created new function with from local templates using `faas-cli new java11-test --lang java11 -f <path of template>`
3. Build function `faas-cli build -f ./java11-test.yml`
4. Deploy function `faas-cli deploy -f ./java11-test.yml`
5. Invoke function
There should be no impact. As only kube-probe log is disabled
> Use of-watchdog 0.9.3 to suppress custom health check logging messages

- template/node16/index.js
- template/node17/index.js
Fix a small type in listening message for node16 and node17 templates 
Fixes #
> Fix a listening message typo

- .gitignore
- template/go/Dockerfile
- template/go/function/go.mod
- template/go/go.mod
- template/go/go.work
Support Go 1.18 and improve module support using Workspaces
Fixes #
See https://github.com/LucasRoesler/openfaas-golang-template-workspace
- [?] Breaking change (fix or feature that would cause existing functionality to change)
> feat: upgrade to go 1.18 and support modules via workspaces

- README.md
Update README.md - fix node20 name (previously node18)
Fixes #310
Not relevant as it is just a README change.
None, given the template name is wrong, it's just a name change.
> Update README.md - fix node20 name (previously node18)

- template/bun/Dockerfile
- template/csharp/Dockerfile
- template/dockerfile/function/Dockerfile
- template/go/Dockerfile
- template/java11-vert-x/Dockerfile
- template/java11/Dockerfile
- template/node/Dockerfile
- template/node14/Dockerfile
- template/node16/Dockerfile
- template/node17/Dockerfile
- template/node18/Dockerfile
- template/node20/Dockerfile
- template/php7/Dockerfile
- template/php8/Dockerfile
- template/python/Dockerfile
- template/python3-debian/Dockerfile
- template/python3/Dockerfile
- template/ruby/Dockerfile
Update all templates to the latest watchdog version to add support for built-in function authentication.
Support built-in function authentication.
Fixes #
Templates can be used without any changes but users will be able to enable built-in authentication for functions using the templates.
> Update watchdogs for function authentication
